<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitccfedb14af03ecfc66cb9f791a6ae57e
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Tests\\' => 6,
        ),
        'D' => 
        array (
            'Database\\Seeders\\' => 17,
            'Database\\Factories\\' => 19,
        ),
        'A' => 
        array (
            'App\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Tests\\' => 
        array (
            0 => __DIR__ . '/../..' . '/tests',
        ),
        'Database\\Seeders\\' => 
        array (
            0 => __DIR__ . '/../..' . '/database/seeders',
        ),
        'Database\\Factories\\' => 
        array (
            0 => __DIR__ . '/../..' . '/database/factories',
        ),
        'App\\' => 
        array (
            0 => __DIR__ . '/../..' . '/app',
        ),
    );

    public static $classMap = array (
        'App\\Console\\Kernel' => __DIR__ . '/../..' . '/app/Console/Kernel.php',
        'App\\DataTables\\AuthorsDataTable' => __DIR__ . '/../..' . '/app/DataTables/AuthorsDataTable.php',
        'App\\DataTables\\CategoriesDataTable' => __DIR__ . '/../..' . '/app/DataTables/CategoriesDataTable.php',
        'App\\DataTables\\QuotesDataTable' => __DIR__ . '/../..' . '/app/DataTables/QuotesDataTable.php',
        'App\\Exceptions\\Handler' => __DIR__ . '/../..' . '/app/Exceptions/Handler.php',
        'App\\Http\\Controllers\\Admin\\AuthorController' => __DIR__ . '/../..' . '/app/Http/Controllers/Admin/AuthorController.php',
        'App\\Http\\Controllers\\Admin\\CategoryController' => __DIR__ . '/../..' . '/app/Http/Controllers/Admin/CategoryController.php',
        'App\\Http\\Controllers\\Admin\\HomeCategoryController' => __DIR__ . '/../..' . '/app/Http/Controllers/Admin/HomeCategoryController.php',
        'App\\Http\\Controllers\\Admin\\QuoteController' => __DIR__ . '/../..' . '/app/Http/Controllers/Admin/QuoteController.php',
        'App\\Http\\Controllers\\Admin\\StickerController' => __DIR__ . '/../..' . '/app/Http/Controllers/Admin/StickerController.php',
        'App\\Http\\Controllers\\Admin\\TemplateController' => __DIR__ . '/../..' . '/app/Http/Controllers/Admin/TemplateController.php',
        'App\\Http\\Controllers\\Admin\\TitleController' => __DIR__ . '/../..' . '/app/Http/Controllers/Admin/TitleController.php',
        'App\\Http\\Controllers\\Api\\CategoryController' => __DIR__ . '/../..' . '/app/Http/Controllers/Api/CategoryController.php',
        'App\\Http\\Controllers\\Api\\HomeCategoryController' => __DIR__ . '/../..' . '/app/Http/Controllers/Api/HomeCategoryController.php',
        'App\\Http\\Controllers\\Api\\QuoteController' => __DIR__ . '/../..' . '/app/Http/Controllers/Api/QuoteController.php',
        'App\\Http\\Controllers\\Api\\StickerController' => __DIR__ . '/../..' . '/app/Http/Controllers/Api/StickerController.php',
        'App\\Http\\Controllers\\Api\\TemplateController' => __DIR__ . '/../..' . '/app/Http/Controllers/Api/TemplateController.php',
        'App\\Http\\Controllers\\Api\\TitleController' => __DIR__ . '/../..' . '/app/Http/Controllers/Api/TitleController.php',
        'App\\Http\\Controllers\\Auth\\AuthenticatedSessionController' => __DIR__ . '/../..' . '/app/Http/Controllers/Auth/AuthenticatedSessionController.php',
        'App\\Http\\Controllers\\Auth\\ConfirmablePasswordController' => __DIR__ . '/../..' . '/app/Http/Controllers/Auth/ConfirmablePasswordController.php',
        'App\\Http\\Controllers\\Auth\\EmailVerificationNotificationController' => __DIR__ . '/../..' . '/app/Http/Controllers/Auth/EmailVerificationNotificationController.php',
        'App\\Http\\Controllers\\Auth\\EmailVerificationPromptController' => __DIR__ . '/../..' . '/app/Http/Controllers/Auth/EmailVerificationPromptController.php',
        'App\\Http\\Controllers\\Auth\\NewPasswordController' => __DIR__ . '/../..' . '/app/Http/Controllers/Auth/NewPasswordController.php',
        'App\\Http\\Controllers\\Auth\\PasswordResetLinkController' => __DIR__ . '/../..' . '/app/Http/Controllers/Auth/PasswordResetLinkController.php',
        'App\\Http\\Controllers\\Auth\\RegisteredUserController' => __DIR__ . '/../..' . '/app/Http/Controllers/Auth/RegisteredUserController.php',
        'App\\Http\\Controllers\\Auth\\VerifyEmailController' => __DIR__ . '/../..' . '/app/Http/Controllers/Auth/VerifyEmailController.php',
        'App\\Http\\Controllers\\Controller' => __DIR__ . '/../..' . '/app/Http/Controllers/Controller.php',
        'App\\Http\\Controllers\\FilepondController' => __DIR__ . '/../..' . '/app/Http/Controllers/FilepondController.php',
        'App\\Http\\Kernel' => __DIR__ . '/../..' . '/app/Http/Kernel.php',
        'App\\Http\\Middleware\\Authenticate' => __DIR__ . '/../..' . '/app/Http/Middleware/Authenticate.php',
        'App\\Http\\Middleware\\EncryptCookies' => __DIR__ . '/../..' . '/app/Http/Middleware/EncryptCookies.php',
        'App\\Http\\Middleware\\PreventRequestsDuringMaintenance' => __DIR__ . '/../..' . '/app/Http/Middleware/PreventRequestsDuringMaintenance.php',
        'App\\Http\\Middleware\\RedirectIfAuthenticated' => __DIR__ . '/../..' . '/app/Http/Middleware/RedirectIfAuthenticated.php',
        'App\\Http\\Middleware\\TrimStrings' => __DIR__ . '/../..' . '/app/Http/Middleware/TrimStrings.php',
        'App\\Http\\Middleware\\TrustHosts' => __DIR__ . '/../..' . '/app/Http/Middleware/TrustHosts.php',
        'App\\Http\\Middleware\\TrustProxies' => __DIR__ . '/../..' . '/app/Http/Middleware/TrustProxies.php',
        'App\\Http\\Middleware\\UserHasAuthSecretKey' => __DIR__ . '/../..' . '/app/Http/Middleware/UserHasAuthSecretKey.php',
        'App\\Http\\Middleware\\ValidateSignature' => __DIR__ . '/../..' . '/app/Http/Middleware/ValidateSignature.php',
        'App\\Http\\Middleware\\VerifyCsrfToken' => __DIR__ . '/../..' . '/app/Http/Middleware/VerifyCsrfToken.php',
        'App\\Http\\Requests\\Admin\\AuthorStoreRequest' => __DIR__ . '/../..' . '/app/Http/Requests/Admin/AuthorStoreRequest.php',
        'App\\Http\\Requests\\Admin\\AuthorUpdateRequest' => __DIR__ . '/../..' . '/app/Http/Requests/Admin/AuthorUpdateRequest.php',
        'App\\Http\\Requests\\Admin\\CategoryStoreRequest' => __DIR__ . '/../..' . '/app/Http/Requests/Admin/CategoryStoreRequest.php',
        'App\\Http\\Requests\\Admin\\HomeCategoryStoreRequest' => __DIR__ . '/../..' . '/app/Http/Requests/Admin/HomeCategoryStoreRequest.php',
        'App\\Http\\Requests\\Admin\\JsonQuotesRequest' => __DIR__ . '/../..' . '/app/Http/Requests/Admin/JsonQuotesRequest.php',
        'App\\Http\\Requests\\Admin\\QuoteStoreRequest' => __DIR__ . '/../..' . '/app/Http/Requests/Admin/QuoteStoreRequest.php',
        'App\\Http\\Requests\\Admin\\StickerStoreRequest' => __DIR__ . '/../..' . '/app/Http/Requests/Admin/StickerStoreRequest.php',
        'App\\Http\\Requests\\Admin\\TemplateStoreRequest' => __DIR__ . '/../..' . '/app/Http/Requests/Admin/TemplateStoreRequest.php',
        'App\\Http\\Requests\\Admin\\TitleStoreRequest' => __DIR__ . '/../..' . '/app/Http/Requests/Admin/TitleStoreRequest.php',
        'App\\Http\\Requests\\Auth\\LoginRequest' => __DIR__ . '/../..' . '/app/Http/Requests/Auth/LoginRequest.php',
        'App\\Http\\Resources\\CategoryResource' => __DIR__ . '/../..' . '/app/Http/Resources/CategoryResource.php',
        'App\\Http\\Resources\\FilesResource' => __DIR__ . '/../..' . '/app/Http/Resources/FilesResource.php',
        'App\\Http\\Resources\\QuoteResource' => __DIR__ . '/../..' . '/app/Http/Resources/QuoteResource.php',
        'App\\Jobs\\UploadJsonQuotesJob' => __DIR__ . '/../..' . '/app/Jobs/UploadJsonQuotesJob.php',
        'App\\Models\\Author' => __DIR__ . '/../..' . '/app/Models/Author.php',
        'App\\Models\\Category' => __DIR__ . '/../..' . '/app/Models/Category.php',
        'App\\Models\\CategoryQuote' => __DIR__ . '/../..' . '/app/Models/CategoryQuote.php',
        'App\\Models\\Quote' => __DIR__ . '/../..' . '/app/Models/Quote.php',
        'App\\Models\\Traits\\HasFileUpload' => __DIR__ . '/../..' . '/app/Models/Traits/HasFileUpload.php',
        'App\\Models\\User' => __DIR__ . '/../..' . '/app/Models/User.php',
        'App\\Policies\\CategoryPolicy' => __DIR__ . '/../..' . '/app/Policies/CategoryPolicy.php',
        'App\\Policies\\QuotePolicy' => __DIR__ . '/../..' . '/app/Policies/QuotePolicy.php',
        'App\\Providers\\AppServiceProvider' => __DIR__ . '/../..' . '/app/Providers/AppServiceProvider.php',
        'App\\Providers\\AuthServiceProvider' => __DIR__ . '/../..' . '/app/Providers/AuthServiceProvider.php',
        'App\\Providers\\BroadcastServiceProvider' => __DIR__ . '/../..' . '/app/Providers/BroadcastServiceProvider.php',
        'App\\Providers\\EventServiceProvider' => __DIR__ . '/../..' . '/app/Providers/EventServiceProvider.php',
        'App\\Providers\\RouteServiceProvider' => __DIR__ . '/../..' . '/app/Providers/RouteServiceProvider.php',
        'App\\Providers\\TelescopeServiceProvider' => __DIR__ . '/../..' . '/app/Providers/TelescopeServiceProvider.php',
        'App\\Services\\BreadcrumbService' => __DIR__ . '/../..' . '/app/Services/BreadcrumbService.php',
        'App\\Services\\FilePondService' => __DIR__ . '/../..' . '/app/Services/FilePondService.php',
        'App\\View\\Components\\AppLayout' => __DIR__ . '/../..' . '/app/View/Components/AppLayout.php',
        'App\\View\\Components\\Button\\ViewMore' => __DIR__ . '/../..' . '/app/View/Components/Button/ViewMore.php',
        'App\\View\\Components\\Card\\Title' => __DIR__ . '/../..' . '/app/View/Components/Card/Title.php',
        'App\\View\\Components\\Form\\Checkbox' => __DIR__ . '/../..' . '/app/View/Components/Form/Checkbox.php',
        'App\\View\\Components\\Form\\CheckboxGroup' => __DIR__ . '/../..' . '/app/View/Components/Form/CheckboxGroup.php',
        'App\\View\\Components\\Form\\Error' => __DIR__ . '/../..' . '/app/View/Components/Form/Error.php',
        'App\\View\\Components\\Form\\Filepond' => __DIR__ . '/../..' . '/app/View/Components/Form/Filepond.php',
        'App\\View\\Components\\Form\\FlatPicker' => __DIR__ . '/../..' . '/app/View/Components/Form/FlatPicker.php',
        'App\\View\\Components\\Form\\Input' => __DIR__ . '/../..' . '/app/View/Components/Form/Input.php',
        'App\\View\\Components\\Form\\InputGroup' => __DIR__ . '/../..' . '/app/View/Components/Form/InputGroup.php',
        'App\\View\\Components\\Form\\Label' => __DIR__ . '/../..' . '/app/View/Components/Form/Label.php',
        'App\\View\\Components\\Form\\Radio' => __DIR__ . '/../..' . '/app/View/Components/Form/Radio.php',
        'App\\View\\Components\\Form\\RadioGroup' => __DIR__ . '/../..' . '/app/View/Components/Form/RadioGroup.php',
        'App\\View\\Components\\Form\\Select' => __DIR__ . '/../..' . '/app/View/Components/Form/Select.php',
        'App\\View\\Components\\Form\\SelectGroup' => __DIR__ . '/../..' . '/app/View/Components/Form/SelectGroup.php',
        'App\\View\\Components\\Form\\TextArea' => __DIR__ . '/../..' . '/app/View/Components/Form/TextArea.php',
        'App\\View\\Components\\Form\\TextAreaGroup' => __DIR__ . '/../..' . '/app/View/Components/Form/TextAreaGroup.php',
        'App\\View\\Components\\Form\\Toggle' => __DIR__ . '/../..' . '/app/View/Components/Form/Toggle.php',
        'App\\View\\Components\\GuestLayout' => __DIR__ . '/../..' . '/app/View/Components/GuestLayout.php',
        'App\\View\\Components\\Table\\Actions\\View' => __DIR__ . '/../..' . '/app/View/Components/Table/Actions/View.php',
        'App\\View\\Components\\Table\\BodyRow' => __DIR__ . '/../..' . '/app/View/Components/Table/BodyRow.php',
        'App\\View\\Components\\Table\\DropdownFilter' => __DIR__ . '/../..' . '/app/View/Components/Table/DropdownFilter.php',
        'App\\View\\Components\\Table\\HeadRow' => __DIR__ . '/../..' . '/app/View/Components/Table/HeadRow.php',
        'App\\View\\Components\\Table\\NoData' => __DIR__ . '/../..' . '/app/View/Components/Table/NoData.php',
        'App\\View\\Components\\Table\\ToggleBtn' => __DIR__ . '/../..' . '/app/View/Components/Table/ToggleBtn.php',
        'App\\View\\Components\\Tabs\\Tab' => __DIR__ . '/../..' . '/app/View/Components/Tabs/Tab.php',
        'App\\View\\Components\\Tabs\\TabHeader' => __DIR__ . '/../..' . '/app/View/Components/Tabs/TabHeader.php',
        'App\\View\\Components\\Ui\\Breadcrumb' => __DIR__ . '/../..' . '/app/View/Components/Ui/Breadcrumb.php',
        'App\\View\\Components\\Ui\\MediaFilePreview' => __DIR__ . '/../..' . '/app/View/Components/Ui/MediaFilePreview.php',
        'App\\View\\Components\\Ui\\Sidebar' => __DIR__ . '/../..' . '/app/View/Components/Ui/Sidebar.php',
        'Database\\Factories\\UserFactory' => __DIR__ . '/../..' . '/database/factories/UserFactory.php',
        'Database\\Seeders\\AuthorSeeder' => __DIR__ . '/../..' . '/database/seeders/AuthorSeeder.php',
        'Database\\Seeders\\CategorySeeder' => __DIR__ . '/../..' . '/database/seeders/CategorySeeder.php',
        'Database\\Seeders\\DatabaseSeeder' => __DIR__ . '/../..' . '/database/seeders/DatabaseSeeder.php',
        'Database\\Seeders\\QuoteSeeder' => __DIR__ . '/../..' . '/database/seeders/QuoteSeeder.php',
        'Database\\Seeders\\TemplateCategorySeeder' => __DIR__ . '/../..' . '/database/seeders/TemplateCategorySeeder.php',
        'Database\\Seeders\\UserSeeder' => __DIR__ . '/../..' . '/database/seeders/UserSeeder.php',
        'Tests\\CreatesApplication' => __DIR__ . '/../..' . '/tests/CreatesApplication.php',
        'Tests\\Feature\\Auth\\AuthenticationTest' => __DIR__ . '/../..' . '/tests/Feature/Auth/AuthenticationTest.php',
        'Tests\\Feature\\Auth\\EmailVerificationTest' => __DIR__ . '/../..' . '/tests/Feature/Auth/EmailVerificationTest.php',
        'Tests\\Feature\\Auth\\PasswordConfirmationTest' => __DIR__ . '/../..' . '/tests/Feature/Auth/PasswordConfirmationTest.php',
        'Tests\\Feature\\Auth\\PasswordResetTest' => __DIR__ . '/../..' . '/tests/Feature/Auth/PasswordResetTest.php',
        'Tests\\Feature\\Auth\\RegistrationTest' => __DIR__ . '/../..' . '/tests/Feature/Auth/RegistrationTest.php',
        'Tests\\Feature\\ExampleTest' => __DIR__ . '/../..' . '/tests/Feature/ExampleTest.php',
        'Tests\\TestCase' => __DIR__ . '/../..' . '/tests/TestCase.php',
        'Tests\\Unit\\ExampleTest' => __DIR__ . '/../..' . '/tests/Unit/ExampleTest.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitccfedb14af03ecfc66cb9f791a6ae57e::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitccfedb14af03ecfc66cb9f791a6ae57e::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitccfedb14af03ecfc66cb9f791a6ae57e::$classMap;

        }, null, ClassLoader::class);
    }
}
